version: '3.8'

services:
  backend:
    platform: linux/arm64
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-network
    depends_on:
      - db

  db:
    image: mariadb:10.5
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=archimon
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - spring-network
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}
    ports:
      - "8081:80"
    networks:
      - spring-network
    depends_on:
      - db

networks:
  spring-network:

volumes:
  db-data: