openapi: "3.0.1"
servers:
  - url: http://localhost:8080
    description: Local server
info:
  title: API ArchiMon
  version: 1.0.0
  description: API ArchiMon

paths:
  /archimon:
    $ref: 'archimon/archimon.yml'

